### ISSUE TITLE
rolldice crashes with exit status 139

### ISSUE THREAD

**Issue by luisuribe** [sstrickl/rolldice#10]
The mayhem team reports this issue on Debian:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=716255

Thanks!

**Comment by LocutusOfBorg** [comment]
Hi, interestingly enough: 
the code is segfaulting in getopt_long function, but I can avoid the crash by commenting the following code:
``` roll_from_args ``` function and

```
if ( optind == argc ) {
   return roll_from_stdin();
  }
  else {
   return roll_from_args(argv);
}
```

seems then that somewhere optind is not used correctly, or it makes the program misbehave

**Comment by LocutusOfBorg** [comment]
avoinding ```optind``` usage will fix the crash.

**Comment by sstrickl** [comment]
Thanks for the bug report!  (Sorry about the huge delay here.)

I've looked over the command line handling code, and I'm not seeing anything amiss, even keeping in mind the example command line options they provide in `rolldice-report/crash/` from the tarball attached to the [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=716255). I tried running it locally on the latest `HEAD` after the work I just did, and I'm not seeing a crash.  This might be because the bug is no longer valid, or because I'm trying to reproduce under OS X, and so I'm not using the same libc, but unfortunately I don't have a Debian box currently available to me.  Can it be verified that this is still a problem?

**Comment by LocutusOfBorg** [comment]
cloned the master,
dpkg-buildpackage of the debian packaging (without patches)
or ./debian/rules clean build install binary
```
dpkg -i of the deb file
./crash.sh 
./crash.sh: line 19:  5680 Segmentation fault      env -i MALLOC_CHECK_=0 $GDB /usr/games/rolldice "`cat $DIR/argv_1.symb`" "`cat $DIR/argv_2.symb`" "`cat $DIR/argv_3.symb`" < "$DIR/file___dev__stdin.symb"
```

I still get it
